# @package _global_
module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [512]
  transformer_d_model: 512
  transformer_nhead: 8
  transformer_num_layers: 6
  transformer_ffn_dim: 2048
  transformer_dropout: 0.1
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.001

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
  electrodes: 16  # Electrodes per band (32 total)
